name: Dispatcher

on:
  push:
    branches:
      - dev
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        run: mvn clean compile

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run Tests
        run: mvn test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/prod'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Write settings.xml and settings-security.xml
        shell: bash
        run: |
          mkdir -p ~/.m2
          printf "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<settings>\n  <servers>\n    <server>\n      <id>central</id>\n      <username>%s</username>\n      <password>%s</password>\n    </server>\n  </servers>\n</settings>\n" "${{ vars.MAVEN_CENTRAL_USERNAME }}" "${{ secrets.MAVEN_CENTRAL_PASSWORD }}" > ~/.m2/settings.xml
          printf "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<settingsSecurity>\n  <master>%s</master>\n</settingsSecurity>\n" "${{ secrets.MAVEN_CENTRAL_MASTER_PASSWORD }}" > ~/.m2/settings-security.xml
          cat ~/.m2/settings.xml
          cat ~/.m2/settings-security.xml

      - name: Write SSH key
        shell: bash
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519

      - name: Release Snapshot
        if: github.ref == 'refs/heads/dev'
        env:
          MAVEN_GPG_KEY: ${{ secrets.GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn deploy -X -Dgpg.signer=bc

      - name: Release Production
        if: github.ref == 'refs/heads/prod'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAVEN_GPG_KEY: ${{ secrets.GPG_SECRET_KEY }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          git config --global user.email "dev@bronsenproject.nl"
          git config --global user.name "Dev @ BronsEnProject"
          mvn release:prepare release:perform -B -Dgpg.signer=bc
